name: Azure VM Toolkit

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Action to perform"
        required: true
        type: choice
       	options:
  	- start
  	- stop
  	- status
 	- snapshot
  	- start-tag
  	- stop-tag
      vmName:
        description: "Virtual Machine name"
        required: true
        default: "server2022"
      resourceGroup:
        description: "Resource Group"
        required: true
        default: "RG-Lab"

permissions:
  id-token: write
  contents: read

jobs:
  vm-management:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Install Azure PowerShell
        shell: pwsh
        run: |
          Install-Module Az -Repository PSGallery -Scope CurrentUser -Force

      - name: Verify Azure PowerShell context
        shell: pwsh
        run: |
          Get-AzContext
          Get-AzSubscription | Format-Table Name, Id, State

      - name: Execute PowerShell script
        shell: pwsh
        run: |
          $action = "${{ github.event.inputs.action }}"
          $vm = "${{ github.event.inputs.vmName }}"
          $rg = "${{ github.event.inputs.resourceGroup }}"

          Write-Host "Action: $action"
          Write-Host "VM: $vm"
          Write-Host "Resource Group: $rg"

          switch ($action) {
            "start"    { ./modules/vm-start.ps1 -VMName $vm -ResourceGroup $rg }
            "stop"     { ./modules/vm-stop.ps1 -VMName $vm -ResourceGroup $rg }
            "status"   { ./modules/vm-status.ps1 -VMName $vm -ResourceGroup $rg }
	    "start-tag" { ./modules/vm-start-tag.ps1 }
	    "stop-tag" { ./modules/vm-stop-tag.ps1 }
            "snapshot" { ./modules/vm-snapshot.ps1 -VMName $vm -ResourceGroup $rg }
            default    { throw "Invalid action" }
          }
